baseURL = 'https://blog.happtim.com/'

# default language
defaultContentLanguage = "zh-cn"

# Change the default theme to be use when building the site with Hugo
theme = "PaperMod"
	
[languages]
  [languages.zh-cn]
    weight = 1
    title = "Tim的博客"
	languageCode = "zh"
    languageName = "简体中文"
    hasCJKLanguage = true
	[languages.zh-cn.params]
		dateFormat = "2006年01月02日"
	[languages.zh-cn.params.homeInfoParams]
		title = "欢迎访问"
		content = "Welcome to my blog"
    [[languages.zh-cn.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
	[[languages.zh-cn.menu.main]]
      weight = 2
      identifier = "dotnet"
      pre = ""
      post = ""
      name = "DotNet教程"
      url = "/dotnet/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 4
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
  [languages.en]
    weight = 2
    title = "Tim's Blog"
    languageName = "English"
	[languages.en.params.homeInfoParams]
		title = "Hi there wave"
		content = "Welcome to my blog"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
	  
	  
[params]

	mainSections = ["posts"]
	
	env = "production"
	
	disableSpecial1stPost = false

	displayFullLangName = true

	# To show read time in post meta
	showReadingTime = true
	
	# To word count to metadata
	ShowWordCount = true
	
	#To show/hide Table of Contents
	showToc = true
	
	#To keep open ToC by default on page load
	tocOpen = true
	
	#Show BreadCrumb Navigation above single post/page
	showBreadCrumbs =  true
	
	#ToC will float on the left/right side of the page.
	tocSide = "right"
	
	
