baseURL = 'https://blog.happtim.com/'

# default language
defaultContentLanguage = "zh-cn"

# Change the default theme to be use when building the site with Hugo
theme = "PaperMod"
	
[languages]
  [languages.zh-cn]
    weight = 1
    title = "Timçš„åšå®¢"
	languageCode = "zh"
    languageName = "ç®€ä½“ä¸­æ–‡"
    hasCJKLanguage = true
	[languages.zh-cn.params]
		dateFormat = "2006å¹´01æœˆ02æ—¥"
	[languages.zh-cn.params.homeInfoParams]
		title = "æ¬¢è¿è®¿é—®ğŸ‘‹"
		content = "Welcome to my blog"
	[languages.zh-cn.params.editPost]
		URL = "https://github.com/happtim/myblog/tree/main/content"
        Text = "ç¼–è¾‘æ–‡æ¡£" # edit text
        appendFilePath = true # to append file path to Edit link
    [[languages.zh-cn.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "æ–‡ç« "
      url = "/posts/"
      title = ""
	[[languages.zh-cn.menu.main]]
      weight = 2
      identifier = "dotnet"
      pre = ""
      post = ""
      name = "DotNetæ•™ç¨‹"
      url = "/dotnet/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 3
      identifier = "tags"
      pre = ""
      post = ""
      name = "æ ‡ç­¾"
      url = "/tags/"
      title = ""
    [[languages.zh-cn.menu.main]]
      weight = 4
      identifier = "archives"
      pre = ""
      post = ""
      name = "å½’æ¡£"
      url = "/archives/"
      title = ""
  [languages.en]
    weight = 2
    title = "Tim's Blog"
    languageName = "English"
	[languages.en.params.homeInfoParams]
		title = "Hi there wave"
		content = "Welcome to my blog"
	[languages.en.params.editPost]
		URL = "https://github.com/happtim/myblog/tree/main/content"
        Text = "Edit Text" # edit text
        #appendFilePath = true # to append file path to Edit link
    [[languages.en.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "archives"
      pre = ""
      post = ""
      name = "Archives"
      url = "/archives/"
      title = ""
	  
	  
[params]

	mainSections = ["posts"]
	
	env = "production"
	
	disableSpecial1stPost = false

	displayFullLangName = true

	# To show read time in post meta
	showReadingTime = true
	
	# To word count to metadata
	ShowWordCount = true
	
	#To show/hide Table of Contents
	showToc = true
	
	#To keep open ToC by default on page load
	tocOpen = true
	
	#Show BreadCrumb Navigation above single post/page
	showBreadCrumbs =  true
	
	#ToC will float on the left/right side of the page.
	tocSide = "right"

	ShowAllPagesInArchive = true
	
